### ISSUE TITLE
Table of contents on the side

### ISSUE THREAD

**Issue by FichteFoll** [kennethreitz/pep8.org#3]
The page is pretty long and you get lost easily. I suggest displaying a fixed ToC on the side, either left or right, if the page is wide enough (i.e. not on mobile).

Bonus points if the ToC automatically highlights which section you're reading, using JavaScript.

Example: http://euw.leagueoflegends.com/en/news/game-updates/patch/patch-62-notes

**Comment by kennethreitz** [comment]
Ooh, that'd be fancy. I think I technically know how to pull this off, but it would be a huge struggle. 

Any takers? I'll give you cake! :cake:

**Comment by sergiocorreia** [comment]
Brainstorming a bit:
1. The [content generator](https://github.com/kennethreitz/pep8.org/blob/master/content.sh) is not generating the ToC because the `--standalone` option is missing.
2. Thus, running pandoc again creates a nice ToC wrapped in `<div id="TOC">`
3. Now, we would need to show the div on the left side with `position: absolute`, and if the screen if small enough, use `display: none`.
4. To determine whether the screen is small enough, something like this should work: `@media all and (max-width: 600px) { div#TOC { ... } }`.

**Comment by kennethreitz** [comment]
@sergiocorreia correct, I experimented with `--standalone` but wasn't happy with its behavior. All the links are present, though, so we could take that section of the output and play with it.

The output of that command has been heavily modified, for presentation.

**Comment by boegel** [comment]
+1 for this request, it would greatly improve the usability of this page!

**Comment by FichteFoll** [comment]
Added in https://github.com/kennethreitz/pep8.org/pull/6.
